version: '2.2'

services:
    app:
        image: 'angulardockerapp'
        build: '.'
        ports:
            - 3000:80      
        container_name: 'angularsweb'
        
    api:
        image: 'productapi'
        build: 
            dockerfile: Dockerfile
            context: ./src/api/productsapi
        container_name: 'productapi'
        ports:
            - 5000:80       